function [fitresult, gof] = CropAlbFitGro(LAIC, AlbindexC)
%CREATEFIT1(LAIC,ALBINDEXC)
%  Create a fit.
%
%  Data for 'CropAlbFitGro' fit:
%      X Input : LAIC
%      Y Output: AlbindexC
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Dec-2015 12:49:23


%% Fit: 'CropAlbFitGro'.
[xData, yData] = prepareCurveData( LAIC, AlbindexC );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.99;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'CropAlbFitGro' );
h = plot( fitresult, xData, yData );
ylim([0,0.3]);
legend( h, 'AlbindexC vs. LAIC', 'CropAlbFitGro', 'Location', 'NorthEast' );
% Label axes
xlabel LAIC
ylabel AlbindexC
grid on

%Saving r2 (terrible practice, I know)
global r2Alb
r2Alb=gof;


