function [fitresult, gof] = CropAlbFit(LAIC, SNOWC, AlbindexC, COUNTSC)
%CREATEFIT1(LAIC,SNOWC,ALBINDEXC)
%  Create a fit.
%
%  Data for 'CropAlbFit' fit:
%      X Input : LAIC
%      Y Input : SNOWC
%      Z Output: AlbindexC
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Dec-2015 12:47:12


%% Fit: 'CropAlbFit'.
[xData, yData, zData, weights] = prepareSurfaceData(LAIC, SNOWC, AlbindexC,COUNTSC );

% Set up fittype and options.
ft = fittype( 'lowess' );
opts = fitoptions( 'Method', 'LowessFit' );
opts.Normalize = 'on';
opts.Robust = 'Bisquare';
opts.Span = 0.15;
Weights=weights;

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'CropAlbFit' );
% h = plot( fitresult, [xData, yData], zData );
% zlim([0,0.7]);
% legend( h, 'CropAlbFit', 'AlbindexC vs. LAIC, SNOWC', 'Location', 'NorthEast' );
% % Label axes
% xlabel LAIC
% ylabel SNOWC
% zlabel AlbindexC
% grid on
% view( 48.5, 22.0 );

%Saving r2 (terrible practice, I know)
global r2Alb
r2Alb=gof;


