function [fitresult, gof] = CropAlbFitWide(LAIC, SNOWC, AlbindexC, COUNTSC)
%CREATEFIT1(LAIC,SNOWC,ALBINDEXC,COUNTSC)
%  Create a fit.
%
%  Data for 'CropAlbFitWide' fit:
%      X Input : LAIC
%      Y Input : SNOWC
%      Z Output: AlbindexC
%      Weights : COUNTSC
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Aug-2016 14:51:38


%% Fit: 'CropAlbFitWide'.
[xData, yData, zData, weights] = prepareSurfaceData( LAIC, SNOWC, AlbindexC, COUNTSC );

% Set up fittype and options.
ft = fittype( 'lowess' );
opts = fitoptions( 'Method', 'LowessFit' );
opts.Normalize = 'on';
opts.Robust = 'Bisquare';
opts.Span = 0.5;
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'CropAlbFitWide' );
% h = plot( fitresult, [xData, yData], zData );
% zlim([0,0.6]);
% legend( h, 'CropAlbFitWide', 'AlbindexC vs. LAIC, SNOWC with COUNTSC', 'Location', 'NorthEast' );
% % Label axes
% xlabel LAIC
% ylabel SNOWC
% zlabel AlbindexC
% grid on
% view( 50, 20 );

%Saving r2 (terrible practice, I know)
global r2Alb
r2Alb=gof;


