function [fitresult, gof] = DecidAlbFitGro(LAID, AlbindexD)
%CREATEFIT1(LAID,ALBINDEXD)
%  Create a fit.
%
%  Data for 'DecidAlbFitGro' fit:
%      X Input : LAID
%      Y Output: AlbindexD
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Dec-2015 19:18:50


%% Fit: 'DecidAlbFitGro'.
[xData, yData] = prepareCurveData( LAID, AlbindexD );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.Normalize = 'on';
opts.SmoothingParam = 0.99;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'DecidAlbFitGro' );
% h = plot( fitresult, xData, yData );
% legend( h, 'AlbindexD vs. LAID', 'DecidAlbFitGro', 'Location', 'NorthEast' );
% % Label axes
% xlabel LAID
% ylabel AlbindexD
% grid on

%Saving r2 (terrible practice, I know)
global r2Alb
r2Alb=gof;


