function [fitresult, gof] = EvgreenAlbFitGro(LAIE, AlbindexE)
%CREATEFIT1(LAIE,ALBINDEXE)
%  Create a fit.
%
%  Data for 'EvgreenAlbFitGro' fit:
%      X Input : LAIE
%      Y Output: AlbindexE
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Dec-2015 17:14:31


%% Fit: 'EvgreenAlbFitGro'.
[xData, yData] = prepareCurveData( LAIE, AlbindexE );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.Normalize = 'on';
opts.SmoothingParam = 0.99;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
figure( 'Name', 'EvgreenAlbFitGro' );
h = plot( fitresult, xData, yData );
ylim([0,0.3]);
legend( h, 'AlbindexE vs. LAIE', 'EvgreenAlbFitGro', 'Location', 'NorthEast' );
% Label axes
xlabel LAIE
ylabel AlbindexE
grid on

%Saving R2
global r2Alb
r2Alb=gof;


