function [fitresult, gof] = EvgreenAlbFit(LAIE, SNOWE, AlbindexE, COUNTSE)
%CREATEFIT1(LAIE,SNOWE,ALBINDEXE,COUNTSE)
%  Create a fit.
%
%  Data for 'EvgreenAlbFit' fit:
%      X Input : LAIE
%      Y Input : SNOWE
%      Z Output: AlbindexE
%      Weights : COUNTSE
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Dec-2015 17:43:04


%% Fit: 'EvgreenAlbFit'.
[xData, yData, zData, weights] = prepareSurfaceData( LAIE, SNOWE, AlbindexE, COUNTSE );

% Set up fittype and options.
ft = fittype( 'lowess' );
opts = fitoptions( 'Method', 'LowessFit' );
opts.Normalize = 'on';
opts.Robust = 'Bisquare';
opts.Span = 0.15;
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% %Plot fit with data.
% figure( 'Name', 'EvgreenAlbFit' );
% h = plot( fitresult, [xData, yData], zData );
% zlim([0,0.7]);
% legend( h, 'EvgreenAlbFit', 'AlbindexE vs. LAIE, SNOWE with COUNTSE', 'Location', 'NorthEast' );
% % Label axes
% xlabel LAIE
% ylabel SNOWE
% zlabel AlbindexE
% grid on
% view( 40.0, 20.0 );

%Saving r2 (terrible practice, I know)
global r2Alb
r2Alb=gof;



