function [fitresult, gof] = MixedAlbFit(LAIMx, SNOWMx, AlbindexMx,COUNTSMx)
%CREATEFIT1(LAIMX,SNOWMX,ALBINDEXMX,COUNTSMX)
%  Create a fit.
%
%  Data for 'MixedAlbFit' fit:
%      X Input : LAIMx
%      Y Input : SNOWMx
%      Z Output: AlbindexMx
%      Weights : COUNTSMx
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Dec-2015 11:52:38


%% Fit: 'MixedAlbFit'.
%[xData, yData, zData, weights] = prepareSurfaceData( LAIMx, SNOWMx, AlbindexMx, COUNTSMx );

[xData, yData, zData, weights] = prepareSurfaceData( LAIMx, SNOWMx, AlbindexMx, COUNTSMx);

% Set up fittype and options.
ft = fittype( 'lowess' );
opts = fitoptions( 'Method', 'LowessFit' );
opts.Normalize = 'on';
opts.Robust = 'Bisquare';
opts.Span = 0.15;
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'MixedAlbFit' );
% h = plot( fitresult, [xData, yData], zData );
% zlim([0,0.6]);
% legend( h, 'MixedAlbFit', 'AlbindexMx vs. LAIMx, SNOWMx with COUNTSMx', 'Location', 'NorthEast' );
% % Label axes
% xlabel LAIMx
% ylabel SNOWMx
% zlabel AlbindexMx
% grid on
% view( 40.0, 20.0);

%Saving r2 
global r2Alb
r2Alb=gof;

