function [fitresult, gof] = MixedAlbFitGro(LAIMx, AlbindexMx)
%CREATEFIT1(LAIMX,ALBINDEXMX)
%  Create a fit.
%
%  Data for 'MixedAlbFitGro' fit:
%      X Input : LAIMx
%      Y Output: AlbindexMx
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Dec-2015 12:09:29


%% Fit: 'MixedAlbFitGro'.
[xData, yData] = prepareCurveData( LAIMx, AlbindexMx );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.99;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'MixedAlbFitGro' );
% h = plot( fitresult, xData, yData );
% legend( h, 'AlbindexMx vs. LAIMx', 'MixedAlbFitGro', 'Location', 'NorthEast' );
% % Label axes
% xlabel LAIMx
% ylabel AlbindexMx
% grid on

%Saving r2 
global r2Alb
r2Alb=gof;


