function [fitresult, gof] = MosaicAlbFitGro(LAIMo, AlbindexMo)
%CREATEFIT1(LAIMO,ALBINDEXMO)
%  Create a fit.
%
%  Data for 'MosaicAlbFitGro' fit:
%      X Input : LAIMo
%      Y Output: AlbindexMo
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Dec-2015 13:33:11


%% Fit: 'MosaicAlbFitGro'.
[xData, yData] = prepareCurveData( LAIMo, AlbindexMo );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = .99;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
% 
% % %Plot fit with data.
% figure( 'Name', 'MosaicAlbFitGro' );
% h = plot( fitresult, xData, yData );
% legend( h, 'AlbindexMo vs. LAIMo', 'MosaicAlbFitGro', 'Location', 'NorthEast' );
% % Label axes
% xlabel LAIMo
% ylabel AlbindexMo
% grid on

%Saving r2 
global r2Alb
r2Alb=gof;


