function [fitresult, gof] = UrbanAlbFit(LAIU, SNOWU, AlbindexU, COUNTSU)
%CREATEFIT1(LAIU,SNOWU,ALBINDEXU,COUNTSU)
%  Create a fit.
%
%  Data for 'UrbanAlbFit' fit:
%      X Input : LAIU
%      Y Input : SNOWU
%      Z Output: AlbindexU
%      Weights : CountsU
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Oct-2016 18:29:41


%% Fit: 'UrbanAlbFit'.
[xData, yData, zData, weights] = prepareSurfaceData( LAIU, SNOWU, AlbindexU, COUNTSU );

% Set up fittype and options.
ft = fittype( 'lowess' );
opts = fitoptions( 'Method', 'LowessFit' );
opts.Normalize = 'on';
opts.Robust = 'Bisquare';
opts.Span = 0.15;
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );
% 
% % Plot fit with data.
% figure( 'Name', 'UrbanAlbFit' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'UrbanAlbFit', 'AlbindexU vs. LAIU, SNOWU with CountsU', 'Location', 'NorthEast' );
% % Label axes
% xlabel LAIU
% ylabel SNOWU
% zlabel AlbindexU
% grid on
% view( 30, 30);

%Saving r2 
global r2Alb
r2Alb=gof;



