function [fitresult, gof] = UrbanAlbFitGro(LAIU, AlbindexU)
%CREATEFIT1(LAIU,ALBINDEXU)
%  Create a fit.
%
%  Data for 'UrbanAlbFitGro' fit:
%      X Input : LAIU
%      Y Output: AlbindexU
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Oct-2016 18:41:05


%% Fit: 'UrbanAlbFitGro'.
[xData, yData] = prepareCurveData( LAIU, AlbindexU );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.Normalize = 'on';
opts.SmoothingParam = 0.99;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'UrbanAlbFitGro' );
% h = plot( fitresult, xData, yData );
% legend( h, 'AlbindexU vs. LAIU', 'UrbanAlbFitGro', 'Location', 'NorthEast' );
% % Label axes
% xlabel LAIU
% ylabel AlbindexU
% grid on

%Saving r2 
global r2Alb
r2Alb=gof;



